import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Artifacts — pi',
  description: 'Generated files and code artifacts',
};

export default function ArtifactsPage() {
  return (
    <div className="flex flex-col gap-6 p-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Artifacts</h1>
        <p className="text-sm text-muted-foreground mt-1">Files and code generated by pi</p>
      </div>
      <p className="text-muted-foreground text-sm">No artifacts yet. Ask pi to create files or code.</p>
    </div>
  );
}
